# Generated by Django 5.2.17 on 2026-10-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(blank=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ilustracion',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
